### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by YaNIND** [jibixyt/AntiToolbox#1]
Add player.yml to save kick player use toolbox 
example
name:
  JibixYT
  17-08-2020

**Comment by jibixyt** [comment]
Why? I mean you could just ban the toolbox users, why u want to save the Player names in a file?

**Comment by YaNIND** [comment]
to see which player was banned or kicked and on what date he was kicked and banned

**Comment by jibixyt** [comment]
Okay i add it later possibly

**Comment by YaNIND** [comment]
okay dad :D
